#!/bin/sh

# 修改root密码
password=$(openssl passwd -1 'admin')
sed -i "s|root::0:0:99999:7:::|root:$password:0:0:99999:7:::|g" /etc/shadow

# 语言设置
uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase="/luci-static/argon"
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname=danxiaonuo
uci commit system

# 设置默认管理IP地址
uci set network.lan.ipaddr='10.8.1.1'
uci set network.lan.netmask='255.255.255.0'
# IPV6设置
uci set network.globals.ula_prefix="ddaa:6666:8888::/48"
uci set network.lan.ip6assign='64'
# 使用内置的 IPv6 管理
uci set dhcp.lan.ra_management='1'
uci commit network

# dhcp设置
uci set dhcp.lan.start='0'
uci set dhcp.lan.limit='255'
uci -q delete dhcp.@dnsmasq[0].server
uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#6053"
uci -q delete dhcp.@dnsmasq[0].filter_aaaa
uci -q delete dhcp.@dnsmasq[0].resolvfile
uci commit dhcp

# 默认开启网络加速
uci set flowoffload.@flow[0]=flow
uci set flowoffload.@flow[0].bbr=1
uci set flowoffload.@flow[0].flow_offloading_hw=1
#uci set flowoffload.@flow[0].dns=1
#uci set flowoffload.@flow[0].dns_server='223.5.5.5,223.6.6.6'
uci commit flowoffload

# WIFI设置
uci set wireless.radio0.country='CN'
uci set wireless.radio0.mu_beamformer='1'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.htmode='HT40'
uci set wireless.default_radio0.ssid='danxiaonuo-2HZ'
uci set wireless.default_radio0.encryption='sae-mixed'
uci set wireless.default_radio0.key='password'
uci set wireless.default_radio0.ieee80211w='1'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.mu_beamformer='1'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.htmode='VHT80'
uci set wireless.default_radio1.ssid='danxiaonuo-5HZ'
uci set wireless.default_radio1.encryption='sae-mixed'
uci set wireless.default_radio1.key='password'
uci set wireless.default_radio1.ieee80211w='1'
uci commit wireless
wifi down && wifi up

# fstab设置
uci set fstab.@global[0].anon_mount=1
uci commit fstab

# samba设置
uci set samba.@samba[0].name='danxiaonuo'
uci set samba.@samba[0].description='danxiaonuo'
uci commit samba

# 芝麻开门
echo 0xDEADBEEF > /etc/config/google_fu_mode

# vim设置
sed -i 's/mouse=/mouse-=/g' /usr/share/vim/*/defaults.vim

# 删除一些页面
rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

ln -sf /sbin/ip /usr/bin/ip

# 替换源地址
sed -i 's/http:/https:/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.ustc.edu.cn/lede#g' /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

# 增加IPV6防火墙
echo "ip6tables -t nat -I POSTROUTING -s $(uci get network.globals.ula_prefix) -j MASQUERADE" >> /etc/firewall.user

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
